name: Secret Scan

on:
  pull_request:
    branches: [staging, main]

  push:
    branches: [staging, main]

  workflow_dispatch:

  schedule:
    - cron: "0 12 * * *" # Daily at 5:45 PM Nepal time

permissions:
  contents: read

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
